export const INSTRUMENTATION_COPY = {
  badge: "电赛仪器仪表",
  heroLine1: "把题目贴进来",
  heroLine2: "直接拿到一套可做的方案",
  heroCopy:
    "这个页面专门用于电子设计竞赛里的仪器仪表类题目。你可以直接输入题目，也可以上传题目截图；系统会优先基于本地知识库生成中文方案，只有在需要时才调用 OCR 辅助识别。",
  sidebarLabel: "使用方式",
  sidebarTitle: "把这些信息写清楚，方案会更稳",
  sidebarSteps: [
    "尽量贴原题，或者给出完整的题目描述。",
    "如果你知道指标、量程、频率范围或限制条件，也一起写进去。",
    "输出会直接面向实现，重点给出架构、模块、风险点和验证步骤。",
  ],
  inputLabel: "题目输入",
  inputTitle: "你想让它解哪道题？",
  placeholder:
    "把完整题目贴在这里；如果你只有截图，也可以不填文字，直接上传题目图片。",
  imageLabel: "题目图片",
  imageHint:
    "上传题目截图或照片。图片会先压缩，再以低消耗方式做 OCR；如果你输入的文字已经足够完整，系统会优先直接使用本地知识库。",
  imageUpload: "上传图片",
  imageReplace: "更换图片",
  imageRemove: "移除图片",
  imageAlt: "已上传的题目图片",
  imageReady: "图片已准备好",
  imageProcessing: "正在压缩图片",
  imageOptimized: "图片已优化完成",
  imageTypeError: "请上传图片文件。",
  imageSizeError: "图片大小请控制在 5 MB 以内。",
  imageReadError: "图片读取失败，请换一张再试。",
  submit: "生成方案",
  generating: "正在生成...",
  helperText:
    "方案推荐主要来自本地知识库。只有在需要识别图片题面时才会使用 OCR，而且会尽量控制消耗。",
  emptyTopic: "请先输入题目文字，或者上传题目图片。",
  requestFailed: "生成方案失败，请稍后重试。",
  outputLabel: "方案输出",
  outputTitle: "生成结果",
  outputEmpty: "右侧还没有方案。先在左侧输入题目，再点击生成。",
  judgementLabel: "题目判断",
  overviewLabel: "总体方案",
  moduleLabel: "模块设计",
  tuningLabel: "调参步骤",
  riskLabel: "风险点",
  verifyLabel: "验证清单",
  recommendationModeOcr: "本次方案结合了图片识别结果和本地知识库。",
  recommendationModeLocal: "本次方案直接来自本地知识库。",
  deployMarker: "中文轻量版",
  versionLabel: "页面版本",
} as const;

export const EXAMPLE_TOPICS = [
  "设计一个信号失真度测量装置，要求测量基波和谐波并给出 THD。",
  "设计一个同轴电缆长度与终端负载检测装置，要求识别开路、短路和匹配负载。",
  "设计一个电感电容测量装置，要求自动切换量程并输出测量结果。",
];
