export const INSTRUMENTATION_COPY = {
  badge: "电赛仪器仪表",
  heroLine1: "把题目贴进来",
  heroLine2: "直接拿到一套可做的方案",
  heroCopy:
    "这个页面专门给电赛仪器仪表题用。你输入题目描述后，系统会优先基于本地蒸馏知识库给出方案；图片识图只在必要时作为轻量辅助。",
  sidebarLabel: "使用方式",
  sidebarTitle: "把这些信息写清楚，方案会更稳",
  sidebarSteps: [
    "尽量贴原题，或者给出完整的题目描述。",
    "如果你知道指标、量程、频率范围或限制条件，也一起写进去。",
    "输出会直接面向实现，重点是架构、模块、风险和验收。",
  ],
  inputLabel: "题目输入",
  inputTitle: "你想让它解哪道题？",
  placeholder: "把完整题目贴在这里；如果你只有截图，也可以不填文字，直接上传图片。",
  imageLabel: "题目图片",
  imageHint:
    "上传题目截图或照片。图片会先压缩，再按低消耗模式做识图；如果文字输入已经足够，系统会优先直接走本地知识库推荐。",
  imageUpload: "上传图片",
  imageReplace: "更换图片",
  imageRemove: "移除图片",
  imageAlt: "已上传的题目图片",
  imageReady: "图片已准备",
  imageProcessing: "正在压缩图片",
  imageOptimized: "图片已优化",
  imageTypeError: "请上传图片文件。",
  imageSizeError: "图片请控制在 5 MB 以内。",
  imageReadError: "图片读取失败，请换一张再试。",
  submit: "生成方案",
  generating: "正在生成...",
  helperText:
    "方案推荐主要来自本地蒸馏数据。Token 消耗基本只在可选识图步骤，并且现在已限制为压缩图片加低细节 OCR。",
  emptyTopic: "先输入题目文字，或者上传题目图片。",
  requestFailed: "生成方案失败，请稍后重试。",
  outputLabel: "方案输出",
  outputTitle: "生成的方案草稿",
  outputEmpty: "右侧还没有方案。先在左边输入题目，再点击生成。",
  planSummary: "总体思路",
  tuningLabel: "调试顺序",
  riskLabel: "风险点",
  verifyLabel: "验收验证",
  recommendationModeOcr: "推荐模式：先识图提字，再走本地蒸馏方案推荐。",
  recommendationModeLocal: "推荐模式：仅使用本地蒸馏方案推荐。",
  ocrBudget: "OCR 预算",
  used: "已用",
  remaining: "剩余",
  requestOcrUsage: "本次 OCR 消耗",
} as const;

export const EXAMPLE_TOPICS = [
  "设计一个信号失真度测量装置，要求测量基波和谐波并给出 THD。",
  "设计一个同轴电缆长度与终端负载检测装置，要求识别开路、短路和匹配负载。",
  "设计一个电感电容测量装置，要求自动切换量程并输出测量结果。",
];
